language: go
go:
  - 1.9.x
  - 1.10.x
sudo: false
env:
  - DEP_VERSION="0.5.0"
before_install:
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
  - chmod +x $GOPATH/bin/dep
install:
  - dep ensure

before_script:
  - go get -u github.com/alecthomas/gometalinter
  - gometalinter --install

script:
  - diff -u <(echo -n) <(gofmt -d -s $(go list ./... | grep -v /vendor/))
  - gometalinter --vendor ./...
  - go test ./...
